### ISSUE TITLE
/29 Default

### ISSUE THREAD

**Issue by jag-sandhu** [chunliu/vnet-capacity-planner#3]
Afternoon,
No matter network range i enter is defaults to /29 and I cannot change it:
![image](https://user-images.githubusercontent.com/47786950/182637145-37b19747-845e-4e5b-9b08-ca3523b185b3.png)

I want to plan for /16 or /20 network but do not know how to change it?

Thanks

**Comment by chunliu** [comment]
The vnet address spaces will be expanded automatically when you add subnets to it. This is a capacity planning tool rather than a network planning tool. It will shows you the minimal address range you need to accommodate the workloads you want to deploy.
